version: '3.7'

services:
  db:
    image: 'postgres:latest'
    container_name: postgres_movies
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - service_data:/var/lib/postgresql/data/
    networks:
      - django_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_movies
    ports:
      - "3333:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - db:db
    depends_on:
      - db
    networks:
      - django_network

  web_backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_movies
    command: ["/entrypoint_backend.sh"]
    environment:
      - PYTHONUNBUFFERED=True
    env_file:
      - .env
    volumes:
      - ./backend:/code
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - django_network

  web_frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_movies
    command: ["/entrypoint_frontend.sh"]
    environment:
      - PYTHONUNBUFFERED=True
    volumes:
      - ./frontend:/code
    ports:
      - "8000:8000"
    networks:
      - django_network

volumes:
  service_data:
    driver: local

networks:
  django_network:
    driver: bridge
